### ISSUE TITLE
spaces/favorite songs

### ISSUE THREAD

**Issue by t0000** [debfx/spotify-playlists#3]
Hello
- there are problems when importing if the playlist contains a space -> exampl: my playlist
- the favorite songs are exported to Saved tracks.xspf, but when you import it it is a new playlist and no longer favorite songs

Regards

**Comment by debfx** [comment]
* Playlists with spaces work fine for me. What exactly are the problems?
* Right, but you can just add all tracks from the playlist to your liked songs and then delete the playlist. I'm not going to special case this in the import functionality.
